version: '3.7'

networks:
  mia:
    name: mia
    driver: bridge

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - mia
  api:
    build: ./backend
    env_file:
      - ./.env
    container_name: mia-api
    restart: always
    networks:
      - mia
    ports:
      - 3000:3000
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    container_name: mia-frontend
    restart: always
    networks:
      - mia
    ports:
      - 80:80
    depends_on:
      - api